name: Julia Run

on:
  push:
    branches:
      - master # or your default branch

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        julia-version: ["1.6", "1.9", "1.11"] # Or specify exact versions like "1.9.3"
        arch: ["x64"] # Or specify "x86" if needed.
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1 # This will cache Julia packages and artifacts
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.add(url=\"https://oauth:glpat-L_nSf9MGmzxPG3uaPacn@gitlab.math.ubc.ca/akumah/SealSolver.jl.git\"); Pkg.add(\"URL\")'
      - name: Run tests
        run: julia -e 'include(\"main.jl\"); prime_solver(), run_complete_set()'
