name: Run Julia Script and Store Results

on:
  push:
    branches:
      - master 

jobs:
  run_julia:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Julia
      uses: julia-actions/setup-julia@latest
      with:
        version: '1.11'

    - name: Install Dependencies
      run: |
        julia -e 'using Pkg; Pkg.add(url="https://oauth:glpat-L_nSf9MGmzxPG3uaPacn@gitlab.math.ubc.ca/akumah/SealSolver.jl.git");'

    # - name: Create Results Directory
    #   run: mkdir results

    - name: Run Julia Script
      run: julia -e 'include("main.jl"); prime_solver(); run_complete_set();'

    - name: Archive Results
      uses: actions/upload-artifact@v4
      with:
        name: julia-results-grid_4-case-3
        path: grid_4-case-3/

    - name: Archive Results
      uses: actions/upload-artifact@v4
      with:
        name: julia-results-grid_4-case-4
        path: grid_4-case-4/